ktor:
  application:
    modules:
      - com.coderse.ApplicationKt.module
  deployment:
    port: 8080

jwt:
  issuer: "http://localhost"
  audience: "my-audience"
  realm: "my realm"
  secret: "dasdasdasd"
